# Generated by Django 3.0.3 on 2020-06-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('detial', models.CharField(max_length=100)),
                ('bedcount', models.CharField(max_length=10)),
                ('avalidbed', models.CharField(max_length=10)),
                ('outbed', models.CharField(max_length=10)),
            ],
        ),
    ]
